// Application state shared by every panel.
#ifndef SSSTUDIO_GUI_APP_H
#define SSSTUDIO_GUI_APP_H

#include <atomic>
#include <cstdint>
#include <deque>
#include <filesystem>
#include <functional>
#include <map>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

#include <SDL3/SDL.h>

#include "ssstudio/asset_cache.h"
#include "ssstudio/build.h"
#include "ssstudio/cache.h"
#include "ssstudio/compiler.h"
#include "ssstudio/graph.h"
#include "ssstudio/lint.h"
#include "ssstudio/project.h"
#include "ssstudio/settings.h"
#include "ssstudio/theme_pack.h"
#include "ssstudio/shader_import.h"

#include "file_dialog.h"
#include "scene/scene.h"

namespace ssstudio::gui {

class PreviewRenderer;
class TextureRegistry;

// One open shader: the editor buffer plus everything the last compile produced.
struct Document {
    std::string id;
    std::filesystem::path path;
    Stage stage = Stage::Fragment;
    std::string text;
    bool dirty = false;
    bool compiling = false;
    bool compiled_ok = false;
    // Latched by the first successful compile and never cleared. The preview
    // uses it to tell "not ready yet" apart from "was working, broken right now".
    bool ever_compiled_ok = false;
    double last_compile_ms = 0.0;
    Diagnostics diagnostics;
    Reflection reflection;
    // The blob the last successful compile produced. One PreviewRenderer is
    // shared by every open project, so switching projects has to hand it this
    // project's shaders again; without the blob that would mean recompiling
    // everything on every tab switch.
    std::vector<std::uint8_t> spirv;
    /// The same compile, translated to whatever binary format the preview device
    /// accepts (PreviewRenderer::preview_format). Only a Vulkan device takes the
    /// SPIR-V above directly, so this is what the renderer is actually handed;
    /// on Vulkan the two hold the same bytes.
    std::vector<std::uint8_t> preview_blob;
    std::filesystem::file_time_type disk_time{};
    bool external_change_pending = false;
    int cursor_line = 1;

    std::vector<std::string> undo_snapshots;
    std::size_t undo_cursor = 0;

    // A pinned version for A/B compare: the text that produced it and the SPIR-V
    // it compiled to, so two revisions can be previewed side by side.
    bool has_pinned = false;
    std::string pinned_text;
    std::vector<std::uint8_t> pinned_spirv;
    Reflection pinned_reflection;

    // Set when this shader's source is generated by a graph. The text editor is
    // read-only until the graph is detached.
    bool generated_by_graph = false;

    /// Whether this shader has a tab in the editor.
    ///
    /// Closing a tab is an editor-space gesture, not a project one: the document
    /// stays right here with its text, its unsaved edits, its diagnostics and
    /// its compiled blob, so the preview keeps drawing it, a build still
    /// includes it, Save all still saves it, and reopening costs nothing. Only
    /// the editor panel reads this. Removing a shader from the project is
    /// App::remove_shader, and is a different thing entirely.
    bool open_in_editor = true;
};

/// Pointer state over the preview image, in the coordinate system a fullscreen
/// fragment shader works in: pixels, origin bottom-left. Shaders written to the
/// common web-shader convention expect a four-component mouse uniform whose
/// components carry click state as sign, which is assembled from this.
struct PreviewMouse {
    /// Where the pointer was while a button was last held. Retained after
    /// release, which is what a drag-driven shader expects to see.
    float x = 0.0f;
    float y = 0.0f;
    /// Where the button most recently went down.
    float click_x = 0.0f;
    float click_y = 0.0f;
    /// A button is held over the preview image this frame.
    bool down = false;
    /// A button went down over the preview image this frame, and only this one.
    bool pressed = false;
};

/// Which starter source a new shader is written from.
enum class ShaderTemplate {
    /// The stage's standard template: correct SDL register spaces, something
    /// that compiles on the first try, and the rules spelled out in comments.
    Standard,
    /// Vertex stage only: covers the screen from the vertex index and binds no
    /// vertex buffer. The half a fullscreen fragment shader wants. Falls back to
    /// Standard for the stages that have no such form.
    FullscreenTriangle,
    /// An empty file, for pasting something in. It will not compile until there
    /// is something in it, and the diagnostics will say so.
    Empty,
};

// Docking layout presets. Each arranges the same panels for a different task.
enum class LayoutPreset { Write, Tune, Present, Build, Graph, Scene };

/// The arrangement a fresh install opens with, and the one View > Reset layout
/// goes back to. Every launch after the first restores whatever the user left
/// on screen instead (see App::layout_path_).
inline constexpr LayoutPreset kDefaultLayout = LayoutPreset::Write;

// ---------------------------------------------------------------------------
// One open project and everything the UI shows about it.
//
// Several projects can be open at once; the window's project tab bar picks the
// active one. Every panel reads project state through App's accessors, and those
// forward to the active session, so a tab switch moves the whole UI to the other
// project at once and nothing can be edited in one project while another is on
// screen. That is why panel selections that name something inside a project -
// which shader the preview draws, which build profile is chosen, which node or
// entity is selected - live here rather than in a panel-local static.
// ---------------------------------------------------------------------------
struct ProjectSession {
    // Unique for the lifetime of this session and never reused. It scopes the
    // compiler queue, the per-document editor states, and the ImGui ids of the
    // project tab, so two projects that share a shader id stay apart.
    std::string key;

    Project project;
    std::vector<Document> documents;
    std::string active_id;

    /// The shader ids of the open tabs, in the order they are shown.
    ///
    /// Refreshed each frame by the editor panel from the tab bar itself, because
    /// the bar is reorderable and dragging a tab is the only thing that changes
    /// this. It lives here rather than in a panel-local static for the reason
    /// given above: it names shaders inside one project, and two open projects
    /// must not share it. It is also what "close the tabs to the right" is
    /// measured against, and what is written to the settings so a project opens
    /// arranged the way it was left.
    std::vector<std::string> tab_order;

    // Pending "show me this line" request; see App::reveal().
    std::string reveal_id;
    int reveal_line = 0;

    std::map<std::string, Graph> graphs;  // by shader id

    Scene scene;
    bool scene_open = false;
    bool scene_dirty = false;

    /// Shader time in seconds, advanced by the frame delta scaled by
    /// PreviewSettings::speed. Frozen while the preview is paused.
    double preview_time = 0.0;
    /// How much shader time the last advanced frame added. This is what a
    /// shader sees as its frame delta, so it carries the speed multiplier for
    /// the same reason preview_time does. Zero while paused.
    double preview_delta = 0.0;
    /// Frames the preview has advanced since the project opened or since the
    /// last reset. Counted rather than derived from time: a shader that seeds
    /// itself on frame zero, or hashes the frame number, needs a number that
    /// only ever moves forward one step at a time - scrubbing time must not
    /// make it jump, and a paused preview must not make it climb.
    std::uint64_t preview_frame = 0;
    /// Pointer state over this project's preview image, refreshed once per frame
    /// by the preview panel.
    PreviewMouse preview_mouse;

    // Only one build runs at a time across the app, but the report belongs to
    // the project that was built and has to still be there when its tab comes
    // back to the front.
    bool build_running = false;
    std::vector<BuildProgress> build_progress;
    BuildReport last_report;

    // Panel state that names something inside this project.
    std::string preview_vertex;
    std::string preview_fragment;
    std::string build_profile;
    std::string graph_selected_node;
    std::string scene_selected_entity;

    // What "Close project" has to warn about. The manifest is written out as it
    // changes, so unsaved work is the editor buffers and the scene.
    bool has_unsaved_changes() const;
};

struct Action {
    std::string id;
    std::string label;
    std::string shortcut;   // display form, e.g. "Ctrl+B"
    std::function<void()> run;
    std::function<bool()> enabled;
};

class App {
public:
    App();
    ~App();

    bool init(SDL_Window* window, SDL_GPUDevice* device);
    void shutdown();

    // Called once per frame between ImGui::NewFrame() and ImGui::Render().
    void frame(float delta_seconds);

    bool wants_quit() const { return quit_requested_; }

    /// Starts quitting. Projects with unsaved work are put through the same
    /// close confirmation as File > Close, one at a time; cancelling any of them
    /// cancels the quit. The window closes once every project has been dealt
    /// with.
    void request_quit();

    // --- projects ---------------------------------------------------------
    /// Opens a project in a new tab and makes it active. A project that is
    /// already open is brought forward instead of being opened twice: two tabs
    /// over one directory would be two editor buffers over one file.
    bool open_project(const std::filesystem::path& path);
    bool new_project(const std::filesystem::path& dir, const std::string& name, Language language);

    // Ask for a project interactively. new_project opens the in-app form (which
    // has its own Browse button); open_project goes straight to the native
    // picker, since there is nothing else to fill in.
    /// Asks for a file with the native picker, delivering the choice on the main
    /// thread. Panels go through here rather than owning a dialog of their own:
    /// only one can be open at a time, and this is where that constraint lives.
    void prompt_for_file(const std::string& title, const std::filesystem::path& start,
                         const std::vector<FileFilter>& filters,
                         std::function<void(const std::filesystem::path&)> on_pick);
    /// True while a picker is up, so a button that would open a second one can
    /// be disabled rather than doing nothing.
    bool file_dialog_busy() const;

    void prompt_new_project();
    void prompt_open_project();
    /// Where new projects go, and the fallback starting point for the Open
    /// dialog. The configured directory from Settings when there is one, and
    /// otherwise the built-in default: the examples/ directory shipped beside
    /// the application, or the user's Documents folder when there is none.
    ///
    /// Always returns a path; it is not guaranteed to exist, because the answer
    /// is a suggestion the user is free to edit rather than a directory this is
    /// entitled to create.
    std::filesystem::path projects_dir() const;

    bool save_all();
    bool save_document(Document& doc);

    /// Closes the active project only, never the others. Unsaved editor buffers
    /// put the confirmation modal up first; the close happens once it is
    /// answered.
    void close_project();

    /// Every open project, in tab order, and the index of the active one
    /// (negative when nothing is open).
    const std::vector<std::unique_ptr<ProjectSession>>& sessions() const { return sessions_; }
    int active_session_index() const { return active_session_; }

    /// Makes the session at `index` the one the whole UI is looking at.
    void activate_session(int index);

    /// Steps to the next or previous project tab, wrapping around. What
    /// Ctrl+Tab does.
    void cycle_session(int delta);

    /// Asks to close one session by index, which is what a tab's close button
    /// and File > Close project both do.
    void request_close_session(int index);

    /// Reopens the projects recorded from the last run, in the order they were
    /// in, and brings the one that was in front back to the front. Called at
    /// startup only when no project path was given on the command line. Does
    /// nothing when the feature is switched off in Settings; projects that have
    /// since moved or been deleted are reported and skipped.
    void restore_session();

    /// Identifies the active session for panel state that has to be kept apart
    /// per project, such as the editor's caret and scroll positions. Empty when
    /// no project is open.
    const std::string& active_session_key() const;

    /// Drops every recent-project entry whose manifest is gone from disk and
    /// writes the settings back out. Both the File menu and the landing screen
    /// offer this, so the erase lives here rather than in either of them.
    void forget_missing_projects();
    /// Drops one entry from the recent list. The bulk version above is the right
    /// gesture after a folder has been moved; this one is for the single project
    /// that is not coming back, without taking the others with it.
    void forget_project(const std::filesystem::path& manifest);
    /// Empties the recent list outright. For a list that has filled up with
    /// one-off projects, or for handing the machine to somebody else: erasing
    /// ten entries one at a time is ten gestures for what is a single decision.
    /// A project that is still open is unaffected - it is listed separately, and
    /// opening it again puts it back at the front.
    void clear_recent_projects();
    bool project_open() const { return active_session_ >= 0; }

    /// The active project. Returns an empty placeholder when nothing is open, so
    /// a panel that reads it before checking project_open() gets defaults rather
    /// than a dangling reference.
    Project& project();
    AppSettings& settings() { return settings_; }
    void save_settings_now();

    /// The theme in effect, resolved. Panels paint from this rather than from
    /// literals, so one theme change moves every colour that belongs to it.
    const ResolvedTheme& theme() const { return theme_; }

    /// The installed packs by id, for the picker in Settings.
    const std::map<std::string, ThemePack>& theme_packs() const { return theme_packs_; }

    /// The themes/ directory a person drops packs into: the one beside
    /// settings.toml. The other two roots are the application's own and the
    /// project's, and neither is somewhere to put a theme of one's own.
    std::filesystem::path user_themes_dir() const;

    /// The themes/ directory that shipped with the application, wherever this
    /// build put it. Empty when there is none - a development build run from a
    /// tree that has not been built yet, for instance.
    std::filesystem::path shipped_themes_dir() const;

    /// Re-reads the themes/ directories. Called at startup and whenever the
    /// user asks for the list again.
    void reload_theme_packs();

    /// The window came back to the foreground. Checks the active theme pack for
    /// an edit, when the user has asked for that.
    void window_focus_gained();

    /// Resolves settings_.editor.color_theme and hands it to ImGui. Also
    /// refreshes the syntax colours the user has not pinned, which is what
    /// makes a theme change apply to the editor as well as to the chrome.
    void apply_current_theme();

    /// Drops remembered editor state for projects that have fallen off both the
    /// recent list and the open list. There is no way back to those from inside
    /// the app, so which of their tabs were closed is dead weight - and this is
    /// what keeps AppSettings::closed_shaders from growing without end.
    void forget_stale_editor_state();

    /// Copies the open tabs into the settings so the next run can reopen them.
    /// Called after anything that changes which projects are open or which is in
    /// front, rather than only at shutdown, so a crash costs at most the last
    /// change instead of the whole session.
    void remember_open_projects();

    // --- documents --------------------------------------------------------
    std::vector<Document>& documents();
    Document* active_document();
    Document* find_document(const std::string& id);
    void focus_document(const std::string& id);
    void mark_dirty(Document& doc);

    /// Closes a shader's editor tab. Nothing is written, nothing is discarded
    /// and the project is untouched; see Document::open_in_editor. Unknown ids
    /// are ignored, so a caller may close a list without checking it twice.
    void close_document(const std::string& id);

    /// Puts a closed shader's tab back and brings it to the front.
    void open_document(const std::string& id);

    /// Every shader of the active project whose tab is closed, in project order.
    /// What the "Reopen" lists offer.
    std::vector<std::string> closed_documents() const;

    /// Copies the active project's tab arrangement - the order and which are
    /// closed - into the settings, so the next session opens the way this one
    /// was left. The write to disk is deferred to the end of the frame, so
    /// closing ten tabs at once still costs one.
    void remember_editor_state();

    /// The order the active project's tabs are shown in, left to right. Empty
    /// when no project is open, or before the editor has drawn them once.
    const std::vector<std::string>& tab_order() const;

    /// Records the order the editor laid the tabs out in. Called every frame by
    /// the editor panel; a call that changes nothing costs nothing, and one that
    /// does is what marks the arrangement for saving.
    void set_tab_order(std::vector<std::string> order);

    // Focus a shader and scroll its editor to a line, so a diagnostic can take
    // the user to the code it is about. The editor panel consumes the request on
    // the next frame it draws; line <= 0 means "just show the file".
    void reveal(const std::string& shader_id, int line);
    const std::string& reveal_request_id() const;
    int reveal_request_line() const;
    void clear_reveal_request();

    /// Registers an existing source file as a shader of the project, opens an
    /// editor buffer for it and compiles it.
    ///
    /// `language` is worth passing whenever it is known: left unset the shader
    /// inherits Project::default_language, which is HLSL for every scaffolded
    /// project and would hand a GLSL file to the wrong front end.
    void add_shader(const std::filesystem::path& source, Stage stage, const std::string& id,
                    std::optional<Language> language = std::nullopt);

    // --- authoring shaders -------------------------------------------------
    /// Opens the New shader form. The fields start from the active project's
    /// defaults, so the quickest path through it is a name and Enter.
    void prompt_new_shader();

    /// Writes a starter source file and registers it as a shader of the active
    /// project, which is what the New shader form does on Create.
    ///
    /// `relative` is where the file goes, relative to the project root; an
    /// existing file is never overwritten.
    ///
    /// Returns false with something worth putting in the form in `out_error`.
    bool create_shader(const std::string& id, Stage stage, std::optional<Language> language,
                       const std::filesystem::path& relative, ShaderTemplate which,
                       std::string& out_error);

    /// Changes a shader's id and moves its file, carrying everything that names
    /// it along: bindings, provenance, the pass order, its graph, the preview
    /// selection and any scene material that referred to it.
    ///
    /// The shader's pinned key is deliberately left alone. A key is what a built
    /// pack is addressed by, so renaming a shader has to stay a source-level
    /// change rather than something that breaks a shipped binary.
    bool rename_shader(const std::string& id, const std::string& new_id,
                       const std::filesystem::path& new_relative, std::string& out_error);

    /// Copies a shader - the editor buffer rather than what is on disk, so a
    /// duplicate taken mid-edit is the version on screen - under a fresh id and
    /// filename, and brings the copy forward. Bindings are copied with it.
    bool duplicate_shader(const std::string& id, std::string& out_error);

    /// Puts the rename form up for one shader. Does nothing when the id names
    /// nothing in the active project.
    void prompt_rename_shader(const std::string& id);

    /// Puts the delete confirmation up for one shader. Removing a shader is
    /// never immediate: the confirmation is also where deleting the file itself
    /// is chosen, and that is not undoable.
    void prompt_delete_shader(const std::string& id);

    // --- import -----------------------------------------------------------
    /// Opens the fullscreen-shader import form.
    void prompt_import_shader();
    /// Wraps and lands one import in the active project. Returns false and fills
    /// `out_error` with something worth showing in the form; the details always
    /// go to the diagnostics log as well.
    bool import_fullscreen_shader(const ImportRequest& request, std::string& out_error);
    /// Drops a shader from the project and closes its buffer. With
    /// `delete_file` the source file and any graph beside it are erased too;
    /// without it they are left on disk and only the manifest entry goes.
    void remove_shader(const std::string& id, bool delete_file = false);

    // --- compilation ------------------------------------------------------
    void schedule_compile(Document& doc, bool immediate);
    void compile_all();
    CompilerService& compiler() { return *compiler_; }
    std::string backend_name() const { return backend_name_; }

    // --- build ------------------------------------------------------------
    void start_build(const std::string& profile_name, bool dry_run);

    /// True while the active project is being built. Its progress and its report
    /// belong to that project and stay with it across a tab switch.
    bool build_running() const;

    /// True while any project is being built. One build runs at a time, so this
    /// is what disables the Build buttons.
    bool build_busy() const { return build_busy_; }

    /// The name of the project whose build is running, for the "another project
    /// is building" note. Empty when nothing is building.
    std::string building_project_name() const;

    const BuildReport& last_report() const;
    std::vector<BuildProgress> build_progress_snapshot();

    // --- graphs -----------------------------------------------------------
    Graph* graph_for(const std::string& shader_id);
    void create_graph(const std::string& shader_id);
    void detach_graph(const std::string& shader_id);

    /// Writes the graph file without regenerating the shader from it. What a
    /// node being moved needs: where a node sits cannot change a line of the
    /// generated source, so running codegen for it is work with no result -
    /// and on_graph_changed also writes to disk, which is not something to do
    /// on every frame of a drag.
    void save_graph_layout(const std::string& shader_id);
    // Regenerates the shader source from its graph and recompiles.
    void on_graph_changed(const std::string& shader_id);

    // --- scenes (test harness only) ---------------------------------------
    Scene* active_scene();
    std::vector<std::filesystem::path> available_scenes() const;
    void create_scene_from_template(SceneTemplate which);
    bool open_scene(const std::filesystem::path& path);
    void save_active_scene();
    void close_scene();
    void mark_scene_dirty();

    // --- snapshots and A/B compare ----------------------------------------
    void pin_current_version(Document& doc);
    void clear_pinned_version(Document& doc);
    std::string snapshot_diff(const Document& doc) const;

    CompileCache& cache() { return cache_; }

    /// Files fetched from a URL and kept on disk. Nothing fetches through this
    /// on its own - a download is always something someone asked for.
    AssetCache& assets() { return assets_; }

    // --- preview ----------------------------------------------------------
    PreviewRenderer* preview() { return preview_.get(); }
    /// Every texture the preview samples, shared by all open projects the same
    /// way the renderer is.
    TextureRegistry* textures() { return textures_.get(); }
    // The preview needs a vertex and a fragment shader that have each compiled
    // at least once; until then it has nothing to draw and stays disabled.
    bool preview_ready() const;
    double preview_time() const;
    /// Shader-time seconds the last advanced preview frame added. Never
    /// negative, and never zero while running, so a shader may divide by it.
    double preview_delta() const;
    /// Preview frames advanced since the last reset. See
    /// ProjectSession::preview_frame for why this is counted, not derived.
    std::uint64_t preview_frame() const;
    /// Pointer state over the preview image. Returns a default-constructed value
    /// when no project is open.
    const PreviewMouse& preview_mouse() const;
    /// Records this frame's pointer state. Called by the preview panel, which is
    /// the only place that knows where the image was drawn and how large it is.
    void set_preview_mouse(const PreviewMouse& mouse);
    /// Puts the preview clock, its delta and its frame counter back to zero.
    void reset_preview_time();

    /// True when the preview put an image on screen during the frame that has
    /// just been drawn. The shader clock only advances while it is: a preview
    /// behind another tab, closed, or showing a compile error produces no output
    /// and so has no elapsed time to account for. Without this, coming back to
    /// the Preview tab would jump an animation forward by however long it had
    /// been away.
    bool preview_presented() const { return preview_presented_; }
    /// Called by the preview panel at the moment it draws its image.
    void note_preview_presented() { preview_presented_ = true; }

    /// Which compiled shaders the preview draws. Kept with the project so each
    /// tab comes back showing the pass the user left it on.
    std::string& preview_vertex_choice();
    std::string& preview_fragment_choice();

    /// The build profile the Build panel has selected, per project.
    std::string& build_profile_choice();

    /// The graph node and the scene entity selected in this project's panels.
    std::string& graph_selected_node();
    std::string& scene_selected_entity();

    // --- ui ---------------------------------------------------------------
    /// Rebuilds the docking from a preset. The rearrangement is saved like any
    /// other, so the preset is also what the next launch comes back to.
    void apply_layout(LayoutPreset preset);

    /// Throws away what the user has docked and rebuilds kDefaultLayout.
    void reset_layout();
    void open_command_palette() { command_palette_open_ = true; }
    const std::vector<Action>& actions() const { return actions_; }
    void run_action(const std::string& id);

    void log(Severity severity, std::string message);
    const std::deque<Diagnostic>& log_entries() const { return log_; }

    /// Puts what the preview is failing with into the Diagnostics panel, once
    /// per distinct message.
    ///
    /// The preview redraws every frame, so a failure that lasts is a failure
    /// reported sixty times a second - and a log that repeats one line until it
    /// evicts everything else is worse than no log. An empty message means the
    /// frame drew: the state is reset so that the same failure returning later
    /// is reported again rather than swallowed as a repeat.
    void report_preview_status(const std::string& message);
    /// Empties the Diagnostics panel: the application log, the last build's
    /// messages, and every shader's compiler output.
    ///
    /// None of it is lost so much as put down. The log fills again as things
    /// happen, a build writes its report again, and a shader's errors come back
    /// on the next compile - which, with compile-while-typing on, is the next
    /// keystroke. It is a way to clear the noise and see what arrives next.
    void clear_diagnostics();

    // Panels the app owns; each is a free function taking App&.
    bool show_editor = true;
    bool show_io = true;
    bool show_preview = true;
    bool show_build = true;
    bool show_diagnostics = true;
    bool show_settings = false;
    bool show_graph = false;
    /// The pipeline editor. A window rather than a panel: it is opened to set a
    /// pipeline up and closed again, and it is about the thing the preview is
    /// drawing rather than a view of the project.
    bool show_pipeline_editor = false;

    /// Asks for a panel to come to the front. Multi-viewport is on, but a panel
    /// floating inside the main window is not an OS window, so nothing outside
    /// the app can raise it - which leaves a buried panel with no way back
    /// except through here.
    void request_panel_focus(const char* name);
    /// True when the panel of this name is the one the keyboard is going to. A
    /// docked panel counts when its tab is the visible one, which is the only
    /// reading of "focused" that matches what the user can see.
    bool panel_is_focused(const char* name) const;
    /// Raises whatever asked for it. Called once a frame, after the panels have
    /// been drawn, because ImGui can only focus a window that exists.
    void apply_panel_focus();
    bool show_scene = false;

private:
    void register_actions();
    void draw_menu_bar();
    void draw_project_tabs();
    void draw_close_project_modal();

    /// Advances a pending quit: asks about the next project that has unsaved
    /// work, or sets the quit flag once none is left. Called once a frame after
    /// the confirmation modal has had its say.
    void drive_quit();
    void draw_dockspace();
    void draw_command_palette();
    void draw_new_project_modal();
    void draw_import_modal();
    void draw_new_shader_modal();
    void draw_rename_shader_modal();
    void draw_delete_shader_modal();

    /// Info > Configured paths: every directory and file this application reads
    /// or writes, resolved rather than as configured, and each one copyable.
    void draw_paths_modal();
    /// Info > About app: what this build is, and what it was built with.
    void draw_about_modal();

    /// Fills new_shader_path_ from the id, stage and language currently in the
    /// form. Called while the path field is still following the name, which it
    /// does until the user types in it.
    void sync_new_shader_path();
    // Where a file picker should start: next to the most recent project, else home.
    std::filesystem::path default_browse_dir() const;
    void draw_status_bar();
    void handle_shortcuts();
    void poll_external_changes(float delta_seconds);
    void autosave(float delta_seconds);
    void on_compile_finished(const std::string& session_key, const std::string& id,
                             CompileResult result);

    /// The active session, or null when no project is open. Everything that
    /// reads or writes project state goes through one of these two.
    ProjectSession* active();
    const ProjectSession* active() const;

    /// Looks a session up by its key. Used by anything that outlives the session
    /// it was started for - a compile callback, the build thread's hand-back -
    /// so a result for a project that has since been closed is simply dropped.
    ProjectSession* find_session(const std::string& key);
    int index_of_session(const std::string& key) const;

    /// Tears the session down and removes its tab. Waits for its build if one is
    /// running, because the build thread holds a pointer into it.
    void close_session(int index);

    /// Hands the shared PreviewRenderer this session's compiled shaders and
    /// points the compiler's cache at its directory. Called on every tab switch.
    void bind_session_to_shared_state();

    SDL_Window* window_ = nullptr;
    SDL_GPUDevice* device_ = nullptr;

    AppSettings settings_;
    std::filesystem::path settings_path_;

    /// The theme in effect and the packs available to become it.
    ResolvedTheme theme_ = builtin_resolved_theme("dark");
    std::map<std::string, ThemePack> theme_packs_;

    /// Where packs are looked for: beside the executable, beside settings.toml,
    /// then inside the open project. Later roots win an id collision.
    std::vector<std::filesystem::path> theme_roots() const;

    /// The active pack's file, so an edit to it can be noticed on focus. Not
    /// watching anything while a built-in theme is active: there is no file.
    ThemeWatch theme_watch_;

    /// Open projects in tab order. Held by pointer so a session keeps its
    /// address when another one is opened or closed: the build thread and the
    /// compile callbacks both refer to a session that outlives the frame.
    std::vector<std::unique_ptr<ProjectSession>> sessions_;
    int active_session_ = -1;
    std::uint64_t next_session_serial_ = 1;

    /// A tab switch requested from outside the tab bar - opening a project, or
    /// the Window menu. Consumed by the next frame that draws the tabs.
    std::string pending_activate_key_;

    /// The session whose close is waiting on the confirmation modal, and the
    /// frame flag that opens it. Held by key rather than index because closing
    /// one tab renumbers the rest.
    std::string close_pending_key_;
    bool close_modal_pending_ = false;

    /// Returned by project() and documents() when nothing is open, so a panel
    /// that reads them without checking gets an empty project, not a crash.
    Project null_project_;
    std::vector<Document> null_documents_;
    std::string null_string_;

    std::unique_ptr<CompilerService> compiler_;
    std::string backend_name_ = "none";
    CompileCache cache_;
    AssetCache assets_;

    std::unique_ptr<PreviewRenderer> preview_;
    std::unique_ptr<TextureRegistry> textures_;

    std::thread build_thread_;
    /// True from the moment a build is started until its thread has handed the
    /// report back. One build runs at a time across every open project.
    std::atomic<bool> build_busy_{false};
    /// The session that started the running build, so the report lands on the
    /// right project even if the user switches tabs while it runs.
    std::string build_owner_key_;
    // Set by the build thread when a run ends; the UI thread turns it into a
    // "bring the Build panel forward" on the next frame.
    std::atomic<bool> build_finished_{false};
    bool raise_build_panel_ = false;
    std::mutex build_mutex_;

    std::deque<Diagnostic> log_;
    /// The last preview failure written to the log, so it is written once.
    std::string reported_preview_error_;
    std::vector<Action> actions_;

    FileDialog file_dialog_;

    // State of the New project form. It stays filled in after a failed attempt
    // so the user can correct one field rather than retype everything.
    // Set when the menu asks for the form; consumed by the first frame that
    // draws it, which is the frame that calls ImGui::OpenPopup.
    bool new_project_modal_pending_ = false;
    bool new_project_modal_focus_ = false;
    char new_project_name_[128] = "MyShaders";
    char new_project_location_[1024] = "";
    // 0 == HLSL, 1 == GLSL; the combo is the only thing that writes it.
    int new_project_language_ = 0;
    std::string new_project_error_;

    // --- import form -------------------------------------------------------
    bool import_modal_pending_ = false;
    bool import_modal_focus_ = false;
    /// The pasted source. A std::string rather than a fixed char buffer: a
    /// shader worth importing is routinely longer than any buffer size that
    /// would look reasonable here, and truncating one silently at paste time is
    /// the kind of bug that gets blamed on the compiler.
    std::string import_source_;
    /// Shared code to put ahead of the body, when the source expects some.
    std::string import_common_;
    char import_id_[128] = "";
    char import_url_[512] = "";
    char import_author_[128] = "";
    char import_licence_[192] = "";
    bool import_force_opaque_ = true;
    bool import_show_common_ = false;
    std::string import_error_;
    /// Refreshed whenever the pasted source changes, so the report under the
    /// paste box always describes what is actually in it.
    ImportScan import_scan_;
    bool import_scan_dirty_ = true;

    // --- new shader form ---------------------------------------------------
    bool new_shader_modal_pending_ = false;
    bool new_shader_modal_focus_ = false;
    char new_shader_id_[128] = "";
    char new_shader_path_[512] = "";
    // Index into the stage and language combos below, not a Stage / Language:
    // ImGui::Combo writes an int, and the enums are not contiguous from zero in
    // the order the form lists them.
    int new_shader_stage_ = 1;     // 0 vert, 1 frag, 2 comp
    int new_shader_language_ = 0;  // 0 project default, 1 HLSL, 2 GLSL
    /// The starting point the form has selected. Held as the value rather than
    /// as a combo index, because the entries on offer change with the stage and
    /// an index would silently come to mean a different template.
    ShaderTemplate new_shader_template_ = ShaderTemplate::Standard;
    /// Cleared once the user edits the path field, after which the name stops
    /// rewriting it - a path someone typed is not the form's to overwrite.
    bool new_shader_path_follows_id_ = true;
    std::string new_shader_error_;

    // --- rename form -------------------------------------------------------
    /// Which shader the rename form is about. Held by id rather than by pointer
    /// because the documents vector moves as buffers are opened and closed.
    std::string rename_shader_id_;
    bool rename_modal_pending_ = false;
    bool rename_modal_focus_ = false;
    /// The new name, not the new id: the id is derived from it together with the
    /// stage and the language, the same way the form that created it did.
    char rename_shader_name_[128] = "";
    char rename_shader_path_[512] = "";
    bool rename_path_follows_id_ = true;
    std::string rename_error_;

    // --- delete confirmation -----------------------------------------------
    std::string delete_shader_id_;
    bool delete_modal_pending_ = false;
    bool paths_modal_pending_ = false;
    bool about_modal_pending_ = false;
    /// Off by default: removing a shader from a project is reversible by adding
    /// it back, and erasing the file is not.
    bool delete_shader_file_ = false;

    bool command_palette_open_ = false;
    bool quit_requested_ = false;
    /// Set while a quit is working its way through the projects that still have
    /// unsaved changes. Cleared by cancelling any of the confirmations.
    bool quit_pending_ = false;
    bool layout_initialized_ = false;
    /// Set by the preview panel each frame it presents, read and cleared once a
    /// frame by the clock. It therefore describes the previous frame, which is
    /// the only thing that can be known before the panels have run.
    bool preview_presented_ = false;
    /// The panel waiting to be raised, and how many more frames to keep trying.
    /// A panel shown this frame has no window until the next one, so a single
    /// attempt would miss exactly the case that needs it most.
    std::string focus_panel_;
    int focus_panel_frames_ = 0;
    LayoutPreset pending_layout_ = kDefaultLayout;
    bool layout_pending_ = true;
    /// Where the docking is stored: which panel sits in which node, the split
    /// sizes, the tab order and the floating windows. ImGui's own ini handling
    /// is off (see main.cpp), so this file holds nothing but what the app writes.
    std::filesystem::path layout_path_;

    /// Writes layout_path_ from the docking as it stands. Called at the end of a
    /// frame ImGui has reported a change for, and once more on the way out.
    void save_layout_now();

    /// A tab was opened or closed this frame and the settings have not caught up
    /// yet. Written once at the end of the frame rather than per tab, so a
    /// "close all" is one write rather than one per document.
    bool editor_state_dirty_ = false;

    float watch_timer_ = 0.0f;
    float autosave_timer_ = 0.0f;
};

// Panels (src/gui/panels/*.cpp).

/// Drops the caret and scroll positions the editor keeps for one project's
/// documents. Called when a project closes so the states of a long session do
/// not accumulate, and so reopening a project starts at the top of its files.
void forget_editor_states(const std::string& session_key);

/// Drops the editor state of one document, so a shader that is deleted and
/// later re-added does not come back with the caret of the file it replaced.
void forget_editor_state(const std::string& session_key, const std::string& document_id);

/// Moves one document's editor state to a new id, so a rename keeps the caret
/// and the scroll position where the user left them.
void rename_editor_state(const std::string& session_key, const std::string& old_id,
                         const std::string& new_id);

/// What a shader tab's context menu asked for.
///
/// Nothing here is acted on by the menu itself: it is drawn from inside the loop
/// over the documents, and every one of these changes the vector that loop is
/// walking - or the tab bar it is submitting to. The panel applies them once it
/// has finished.
struct TabMenuRequest {
    /// A shader to copy.
    std::string duplicate;
    /// Shader ids whose tabs should close, already resolved from whichever of
    /// the close commands was picked.
    std::vector<std::string> close;
    /// Shader ids whose tabs should open.
    std::vector<std::string> open;
    /// Put the New shader form up.
    bool new_shader = false;

    bool empty() const {
        return duplicate.empty() && close.empty() && open.empty() && !new_shader;
    }
};

/// The right-click menu on a shader tab.
///
/// `order` is the shader ids in the order their tabs are shown, which is what
/// "to the left" and "to the right" are measured against. Requests are added to
/// `out` rather than run.
void draw_shader_tab_menu(App& app, const Document& doc, const std::vector<std::string>& order,
                          TabMenuRequest& out);

void draw_editor_panel(App& app);
void draw_io_panel(App& app);
void draw_preview_panel(App& app);
void draw_pipeline_panel(App& app);
void draw_build_panel(App& app);
void draw_diagnostics_panel(App& app);
void draw_settings_panel(App& app);
void draw_graph_panel(App& app);
void draw_scene_panel(App& app);

// Theme (src/gui/theme.cpp).
void apply_theme(const ResolvedTheme& theme, float ui_scale);

}  // namespace ssstudio::gui

#endif  // SSSTUDIO_GUI_APP_H
