/* s3pack.h - single-header loader for SDL Shader Studio packs.
 *
 * Generated by @TOOL_VERSION@ for pack layout:
 *     @LAYOUT_SIGNATURE@
 *
 * Usage (one translation unit defines the implementation):
 *
 *     #define S3PACK_IMPLEMENTATION
 *     #include "s3pack.h"
 *
 * C:
 *     S3PACK_Pack pack;
 *     if (!S3PACK_OpenFile(&pack, "shaders@PACK_EXT@")) { SDL_Log("%s", S3PACK_GetError()); }
 *     SDL_GPUShader *vs = S3PACK_CreateShader(device, &pack, SHADER_SPRITE_VERT);
 *     ...
 *     SDL_ReleaseGPUShader(device, vs);
 *     S3PACK_Close(&pack);
 *
 * C++ (RAII, no exceptions unless S3PACK_USE_EXCEPTIONS is defined):
 *     auto pack = s3pack::Pack::open_file("shaders@PACK_EXT@");
 *     if (!pack) { SDL_Log("%s", pack.error()); }
 *     s3pack::Shader vs = pack->shader(device, SHADER_SPRITE_VERT);
 *
 * Options (define before including):
 *     S3PACK_IMPLEMENTATION     compile the implementation here
 *     S3PACK_NO_CPP             suppress the C++ wrapper even in C++ builds
 *     S3PACK_USE_EXCEPTIONS     C++ wrapper throws std::runtime_error on failure
 *     S3PACK_ASSERT(x)          override the assertion macro
 *     S3PACK_LZ4_DECODE(...)    supply an LZ4 block decoder (see below)
 *     S3PACK_ZSTD_DECODE(...)   supply a zstd decoder
 *     S3PACK_MALLOC/S3PACK_FREE override allocation (defaults to SDL_malloc)
 *
 * If the pack was built with compression and no decoder macro is supplied, the
 * loader fails with a clear error instead of handing garbage to the driver.
 *
 * License: same terms as your project. This file is generated output; edit the
 * template in the tool rather than the copy, or take ownership and stop
 * regenerating it.
 */
#ifndef S3PACK_H_INCLUDED
#define S3PACK_H_INCLUDED

#include <SDL3/SDL.h>

#ifdef __cplusplus
extern "C" {
#endif

#define S3PACK_LAYOUT_SIGNATURE "@LAYOUT_SIGNATURE@"
#define S3PACK_VERSION_MAJOR @VERSION_MAJOR@
#define S3PACK_VERSION_MINOR @VERSION_MINOR@

typedef enum S3PACK_Stage {
    S3PACK_STAGE_VERTEX = 0,
    S3PACK_STAGE_FRAGMENT = 1,
    S3PACK_STAGE_COMPUTE = 2
} S3PACK_Stage;

typedef struct S3PACK_BlobRef {
    Uint32 format;             /* SDL_GPU_SHADERFORMAT_* */
    Uint32 offset;
    Uint32 size;
    Uint32 uncompressed_size;
} S3PACK_BlobRef;

typedef struct S3PACK_Entry {
    Uint32 key;
    Uint8 stage;
    Uint8 language;
    Uint8 blob_count;
    Uint8 num_samplers;
    /* For graphics shaders these are simply the storage counts. For compute they
     * are the read-only counts, with the read-write ones below, matching
     * SDL_GPUComputePipelineCreateInfo exactly. */
    Uint8 num_storage_textures;
    Uint8 num_storage_buffers;
    Uint8 num_uniform_buffers;
    Uint8 num_readwrite_storage_textures;
    Uint8 num_readwrite_storage_buffers;
    const char *name;          /* NULL when names were stripped */
    const char *entry_point;
    Uint32 compute_threads[3];
    Uint32 format_mask;
    S3PACK_BlobRef blobs[8];
} S3PACK_Entry;

typedef struct S3PACK_Pack {
    const Uint8 *data;
    size_t size;
    bool owns_data;
    Uint32 flags;
    Uint32 format_mask;
    Uint32 stage_mask;
    Uint32 compression;
    Uint32 shader_count;
    S3PACK_Entry *entries;
    const char *user_section;
    Uint32 user_section_size;
} S3PACK_Pack;

/* --- lifetime ---------------------------------------------------------- */
extern bool S3PACK_OpenMemory(S3PACK_Pack *pack, const void *data, size_t size,
                              bool take_ownership);
extern bool S3PACK_OpenFile(S3PACK_Pack *pack, const char *path);
extern void S3PACK_Close(S3PACK_Pack *pack);
extern const char *S3PACK_GetError(void);

/* --- queries ----------------------------------------------------------- */
extern const S3PACK_Entry *S3PACK_Find(const S3PACK_Pack *pack, Uint32 key);
extern Uint32 S3PACK_PickFormat(const S3PACK_Pack *pack, SDL_GPUDevice *device, Uint32 key);
extern bool S3PACK_IsComputeOnly(const S3PACK_Pack *pack);

/* Copies the blob for `key` in `format` into `out` (size `out_size`), returning
 * the byte count written, or 0 on failure. Pass out == NULL to query the size. */
extern size_t S3PACK_ReadBlob(const S3PACK_Pack *pack, Uint32 key, Uint32 format, void *out,
                              size_t out_size);

/* --- creation ---------------------------------------------------------- */
/* Creates a graphics shader with the counts recorded at build time. Returns
 * NULL and sets S3PACK_GetError() on failure. */
extern SDL_GPUShader *S3PACK_CreateShader(SDL_GPUDevice *device, const S3PACK_Pack *pack,
                                          Uint32 key);

/* Compute equivalent; also reports the thread group size if `out_threads` is
 * non-NULL, so a dispatch can be derived without hardcoding it. */
extern SDL_GPUComputePipeline *S3PACK_CreateComputePipeline(SDL_GPUDevice *device,
                                                            const S3PACK_Pack *pack, Uint32 key,
                                                            Uint32 out_threads[3]);

#ifdef __cplusplus
}  /* extern "C" */
#endif

/* ======================================================================== */
/*                            C++ RAII wrapper                              */
/* ======================================================================== */
#if defined(__cplusplus) && !defined(S3PACK_NO_CPP)

#include <cstddef>
#include <utility>
#ifdef S3PACK_USE_EXCEPTIONS
#include <stdexcept>
#endif

namespace s3pack {

/* Move-only owner of an SDL_GPUShader. */
class Shader {
public:
    Shader() = default;
    Shader(SDL_GPUDevice *device, SDL_GPUShader *shader) : device_(device), shader_(shader) {}
    ~Shader() { reset(); }

    Shader(const Shader &) = delete;
    Shader &operator=(const Shader &) = delete;

    Shader(Shader &&o) noexcept : device_(o.device_), shader_(o.shader_) {
        o.device_ = nullptr;
        o.shader_ = nullptr;
    }
    Shader &operator=(Shader &&o) noexcept {
        if (this != &o) {
            reset();
            device_ = o.device_;
            shader_ = o.shader_;
            o.device_ = nullptr;
            o.shader_ = nullptr;
        }
        return *this;
    }

    void reset() {
        if (device_ && shader_) SDL_ReleaseGPUShader(device_, shader_);
        device_ = nullptr;
        shader_ = nullptr;
    }
    SDL_GPUShader *get() const { return shader_; }
    SDL_GPUShader *release() {
        SDL_GPUShader *s = shader_;
        shader_ = nullptr;
        device_ = nullptr;
        return s;
    }
    explicit operator bool() const { return shader_ != nullptr; }

private:
    SDL_GPUDevice *device_ = nullptr;
    SDL_GPUShader *shader_ = nullptr;
};

/* Move-only owner of an SDL_GPUComputePipeline, carrying its thread group size. */
class ComputePipeline {
public:
    ComputePipeline() = default;
    ComputePipeline(SDL_GPUDevice *device, SDL_GPUComputePipeline *p, const Uint32 threads[3])
        : device_(device), pipeline_(p) {
        for (int i = 0; i < 3; ++i) threads_[i] = threads ? threads[i] : 1;
    }
    ~ComputePipeline() { reset(); }

    ComputePipeline(const ComputePipeline &) = delete;
    ComputePipeline &operator=(const ComputePipeline &) = delete;

    ComputePipeline(ComputePipeline &&o) noexcept : device_(o.device_), pipeline_(o.pipeline_) {
        for (int i = 0; i < 3; ++i) threads_[i] = o.threads_[i];
        o.device_ = nullptr;
        o.pipeline_ = nullptr;
    }
    ComputePipeline &operator=(ComputePipeline &&o) noexcept {
        if (this != &o) {
            reset();
            device_ = o.device_;
            pipeline_ = o.pipeline_;
            for (int i = 0; i < 3; ++i) threads_[i] = o.threads_[i];
            o.device_ = nullptr;
            o.pipeline_ = nullptr;
        }
        return *this;
    }

    void reset() {
        if (device_ && pipeline_) SDL_ReleaseGPUComputePipeline(device_, pipeline_);
        device_ = nullptr;
        pipeline_ = nullptr;
    }
    SDL_GPUComputePipeline *get() const { return pipeline_; }
    Uint32 thread_count(int axis) const { return threads_[axis]; }

    /* Groups needed to cover `total` invocations on the given axis. */
    Uint32 groups_for(Uint32 total, int axis) const {
        const Uint32 t = threads_[axis] ? threads_[axis] : 1;
        return (total + t - 1) / t;
    }
    explicit operator bool() const { return pipeline_ != nullptr; }

private:
    SDL_GPUDevice *device_ = nullptr;
    SDL_GPUComputePipeline *pipeline_ = nullptr;
    Uint32 threads_[3] = {1, 1, 1};
};

/* Move-only owner of the pack itself. */
class Pack {
public:
    Pack() { SDL_zero(pack_); }
    ~Pack() { close(); }

    Pack(const Pack &) = delete;
    Pack &operator=(const Pack &) = delete;

    Pack(Pack &&o) noexcept : pack_(o.pack_), open_(o.open_), error_(o.error_) {
        SDL_zero(o.pack_);
        o.open_ = false;
    }
    Pack &operator=(Pack &&o) noexcept {
        if (this != &o) {
            close();
            pack_ = o.pack_;
            open_ = o.open_;
            error_ = o.error_;
            SDL_zero(o.pack_);
            o.open_ = false;
        }
        return *this;
    }

    static Pack open_file(const char *path) {
        Pack p;
        p.open_ = S3PACK_OpenFile(&p.pack_, path);
        if (!p.open_) p.fail();
        return p;
    }
    static Pack open_memory(const void *data, std::size_t size, bool take_ownership = false) {
        Pack p;
        p.open_ = S3PACK_OpenMemory(&p.pack_, data, size, take_ownership);
        if (!p.open_) p.fail();
        return p;
    }

    void close() {
        if (open_) S3PACK_Close(&pack_);
        open_ = false;
    }

    bool good() const { return open_; }
    explicit operator bool() const { return open_; }
    const char *error() const { return error_ ? error_ : ""; }

    /* Pointer-like access so `pack->shader(...)` reads naturally. */
    Pack *operator->() { return this; }
    const Pack *operator->() const { return this; }

    const S3PACK_Pack &raw() const { return pack_; }
    Uint32 shader_count() const { return pack_.shader_count; }
    bool compute_only() const { return S3PACK_IsComputeOnly(&pack_); }
    const S3PACK_Entry *find(Uint32 key) const { return S3PACK_Find(&pack_, key); }
    bool contains(Uint32 key) const { return find(key) != nullptr; }

    Shader shader(SDL_GPUDevice *device, Uint32 key) {
        SDL_GPUShader *s = S3PACK_CreateShader(device, &pack_, key);
        if (!s) fail();
        return Shader(device, s);
    }

    ComputePipeline compute(SDL_GPUDevice *device, Uint32 key) {
        Uint32 threads[3] = {1, 1, 1};
        SDL_GPUComputePipeline *p = S3PACK_CreateComputePipeline(device, &pack_, key, threads);
        if (!p) fail();
        return ComputePipeline(device, p, threads);
    }

private:
    void fail() {
        error_ = S3PACK_GetError();
#ifdef S3PACK_USE_EXCEPTIONS
        throw std::runtime_error(error_ ? error_ : "s3pack: unknown error");
#endif
    }

    S3PACK_Pack pack_;
    bool open_ = false;
    const char *error_ = nullptr;
};

}  /* namespace s3pack */
#endif /* __cplusplus && !S3PACK_NO_CPP */

/* ======================================================================== */
/*                             Implementation                               */
/* ======================================================================== */
#ifdef S3PACK_IMPLEMENTATION

#include <string.h>

#ifndef S3PACK_MALLOC
#define S3PACK_MALLOC(sz) SDL_malloc(sz)
#endif
#ifndef S3PACK_FREE
#define S3PACK_FREE(p) SDL_free(p)
#endif
#ifndef S3PACK_ASSERT
#define S3PACK_ASSERT(x) SDL_assert(x)
#endif

#define S3PACK_FLAG_COMPRESSED       (1u << 0)
#define S3PACK_FLAG_HAS_REFLECTION   (1u << 1)
#define S3PACK_FLAG_HAS_NAMES        (1u << 2)
#define S3PACK_FLAG_COMPUTE_ONLY     (1u << 3)
#define S3PACK_FLAG_HAS_USER_SECTION (1u << 4)
#define S3PACK_FLAG_KEY16            (1u << 5)
#define S3PACK_FLAG_UNSORTED         (1u << 6)
#define S3PACK_FLAG_BLOBS_FIRST      (1u << 7)
#define S3PACK_FLAG_PADDED64         (1u << 8)

#define S3PACK_COMPRESSION_NONE 0
#define S3PACK_COMPRESSION_LZ4  1
#define S3PACK_COMPRESSION_ZSTD 2

static char s3pack_error_buf[256] = {0};

static bool S3PACK_SetError(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    SDL_vsnprintf(s3pack_error_buf, sizeof(s3pack_error_buf), fmt, ap);
    va_end(ap);
    return false;
}

const char *S3PACK_GetError(void) { return s3pack_error_buf; }

typedef struct S3PACK_Cursor {
    const Uint8 *data;
    size_t size;
    size_t pos;
    bool padded;
    bool ok;
} S3PACK_Cursor;

static Uint8 s3pack_u8(S3PACK_Cursor *c) {
    if (c->pos + 1 > c->size) { c->ok = false; return 0; }
    return c->data[c->pos++];
}
static Uint16 s3pack_u16(S3PACK_Cursor *c) {
    if (c->pos + 2 > c->size) { c->ok = false; return 0; }
    Uint16 v = (Uint16)(c->data[c->pos] | (c->data[c->pos + 1] << 8));
    c->pos += 2;
    return v;
}
static Uint32 s3pack_u32(S3PACK_Cursor *c) {
    if (c->pos + 4 > c->size) { c->ok = false; return 0; }
    Uint32 v = (Uint32)c->data[c->pos] | ((Uint32)c->data[c->pos + 1] << 8) |
               ((Uint32)c->data[c->pos + 2] << 16) | ((Uint32)c->data[c->pos + 3] << 24);
    c->pos += 4;
    return v;
}
static Uint32 s3pack_field(S3PACK_Cursor *c) {
    Uint32 v = s3pack_u32(c);
    if (c->padded) (void)s3pack_u32(c);
    return v;
}

/* Entry stride must match the writer's PackLayout::entry_size(). */
static Uint32 s3pack_entry_stride(bool padded, bool key16, Uint32 blob_count) {
    const Uint32 f = padded ? 8u : 4u;
    Uint32 size = (key16 ? 2u : 4u) + 10u + f * 4u + f * 3u + f + blob_count * (f * 3u);
    const Uint32 align = padded ? 8u : 4u;
    return ((size + align - 1u) / align) * align;
}

static const char *s3pack_string(const Uint8 *base, size_t pack_size, Uint32 string_offset,
                                 Uint32 offset) {
    if (offset == 0) return NULL;
    const size_t at = (size_t)string_offset + offset - 1;
    if (at >= pack_size) return NULL;
    return (const char *)(base + at);
}

bool S3PACK_OpenMemory(S3PACK_Pack *pack, const void *data, size_t size, bool take_ownership) {
    S3PACK_ASSERT(pack != NULL);
    SDL_zerop(pack);
    if (!data || size < 32) return S3PACK_SetError("s3pack: buffer too small to be a pack");

    const Uint8 *bytes = (const Uint8 *)data;
    if (SDL_memcmp(bytes, "@MAGIC@", 4) != 0) {
        return S3PACK_SetError("s3pack: bad magic (expected '@MAGIC@'); this loader was generated "
                               "for layout %s", S3PACK_LAYOUT_SIGNATURE);
    }

    const Uint32 flags = (Uint32)bytes[8] | ((Uint32)bytes[9] << 8) | ((Uint32)bytes[10] << 16) |
                         ((Uint32)bytes[11] << 24);

    S3PACK_Cursor c;
    c.data = bytes;
    c.size = size;
    c.pos = 4;
    c.padded = (flags & S3PACK_FLAG_PADDED64) != 0;
    c.ok = true;

    const Uint16 vmaj = s3pack_u16(&c);
    (void)s3pack_u16(&c); /* minor */
    if (vmaj != S3PACK_VERSION_MAJOR) {
        return S3PACK_SetError("s3pack: pack version %u is not supported (loader expects %u)",
                               (unsigned)vmaj, (unsigned)S3PACK_VERSION_MAJOR);
    }

    pack->flags = s3pack_field(&c);
    pack->shader_count = s3pack_field(&c);
    pack->format_mask = s3pack_field(&c);
    pack->stage_mask = s3pack_field(&c);
    pack->compression = s3pack_field(&c);
    (void)s3pack_field(&c); /* alignment */
    const Uint32 table_offset = s3pack_field(&c);
    (void)s3pack_field(&c); /* blob_offset */
    const Uint32 string_offset = s3pack_field(&c);
    const Uint32 user_offset = s3pack_field(&c);
    const Uint32 user_size = s3pack_field(&c);

    if (!c.ok) return S3PACK_SetError("s3pack: truncated header");
    if (pack->shader_count == 0) return S3PACK_SetError("s3pack: pack contains no shaders");

    pack->entries = (S3PACK_Entry *)S3PACK_MALLOC(sizeof(S3PACK_Entry) * pack->shader_count);
    if (!pack->entries) return S3PACK_SetError("s3pack: out of memory");
    SDL_memset(pack->entries, 0, sizeof(S3PACK_Entry) * pack->shader_count);

    const bool key16 = (pack->flags & S3PACK_FLAG_KEY16) != 0;
    c.pos = table_offset;

    for (Uint32 i = 0; i < pack->shader_count; ++i) {
        S3PACK_Entry *e = &pack->entries[i];
        const size_t entry_begin = c.pos;

        e->key = key16 ? (Uint32)s3pack_u16(&c) : s3pack_u32(&c);
        e->stage = s3pack_u8(&c);
        e->language = s3pack_u8(&c);
        e->blob_count = s3pack_u8(&c);
        e->num_samplers = s3pack_u8(&c);
        e->num_storage_textures = s3pack_u8(&c);
        e->num_storage_buffers = s3pack_u8(&c);
        e->num_uniform_buffers = s3pack_u8(&c);
        e->num_readwrite_storage_textures = s3pack_u8(&c);
        e->num_readwrite_storage_buffers = s3pack_u8(&c);
        (void)s3pack_u8(&c); /* reserved */

        const Uint32 entry_off = s3pack_field(&c);
        const Uint32 name_off = s3pack_field(&c);
        (void)s3pack_field(&c); /* reflection offset */
        (void)s3pack_field(&c); /* reflection size */
        e->compute_threads[0] = s3pack_field(&c);
        e->compute_threads[1] = s3pack_field(&c);
        e->compute_threads[2] = s3pack_field(&c);
        e->format_mask = s3pack_field(&c);

        if (e->blob_count > 8) {
            S3PACK_FREE(pack->entries);
            pack->entries = NULL;
            return S3PACK_SetError("s3pack: entry %u has %u blobs, more than this loader supports",
                                   (unsigned)i, (unsigned)e->blob_count);
        }

        /* Blobs are stored in ascending format order; recover each format from
         * the entry mask by walking the same order. */
        Uint32 mask = e->format_mask;
        for (Uint32 b = 0; b < e->blob_count; ++b) {
            Uint32 bit = mask & (~mask + 1u); /* lowest set bit */
            mask &= ~bit;
            e->blobs[b].format = bit;
            e->blobs[b].offset = s3pack_field(&c);
            e->blobs[b].size = s3pack_field(&c);
            e->blobs[b].uncompressed_size = s3pack_field(&c);
            if ((size_t)e->blobs[b].offset + e->blobs[b].size > size) {
                S3PACK_FREE(pack->entries);
                pack->entries = NULL;
                return S3PACK_SetError("s3pack: blob for key %u lies outside the pack",
                                       (unsigned)e->key);
            }
        }

        e->entry_point = s3pack_string(bytes, size, string_offset, entry_off);
        e->name = s3pack_string(bytes, size, string_offset, name_off);

        if (!c.ok) {
            S3PACK_FREE(pack->entries);
            pack->entries = NULL;
            return S3PACK_SetError("s3pack: truncated entry table");
        }
        c.pos = entry_begin + s3pack_entry_stride(c.padded, key16, e->blob_count);
    }

    if (user_offset && user_size && (size_t)user_offset + user_size <= size) {
        pack->user_section = (const char *)(bytes + user_offset);
        pack->user_section_size = user_size;
    }

    pack->data = bytes;
    pack->size = size;
    pack->owns_data = take_ownership;
    return true;
}

bool S3PACK_OpenFile(S3PACK_Pack *pack, const char *path) {
    size_t size = 0;
    void *data = SDL_LoadFile(path, &size);
    if (!data) return S3PACK_SetError("s3pack: could not read '%s': %s", path, SDL_GetError());
    if (!S3PACK_OpenMemory(pack, data, size, true)) {
        SDL_free(data);
        return false;
    }
    return true;
}

void S3PACK_Close(S3PACK_Pack *pack) {
    if (!pack) return;
    if (pack->entries) S3PACK_FREE(pack->entries);
    if (pack->owns_data && pack->data) SDL_free((void *)pack->data);
    SDL_zerop(pack);
}

const S3PACK_Entry *S3PACK_Find(const S3PACK_Pack *pack, Uint32 key) {
    if (!pack || !pack->entries) return NULL;
    if (pack->flags & S3PACK_FLAG_UNSORTED) {
        for (Uint32 i = 0; i < pack->shader_count; ++i) {
            if (pack->entries[i].key == key) return &pack->entries[i];
        }
        return NULL;
    }
    Uint32 lo = 0, hi = pack->shader_count;
    while (lo < hi) {
        const Uint32 mid = lo + (hi - lo) / 2;
        if (pack->entries[mid].key < key) {
            lo = mid + 1;
        } else if (pack->entries[mid].key > key) {
            hi = mid;
        } else {
            return &pack->entries[mid];
        }
    }
    return NULL;
}

bool S3PACK_IsComputeOnly(const S3PACK_Pack *pack) {
    return pack && (pack->flags & S3PACK_FLAG_COMPUTE_ONLY) != 0;
}

Uint32 S3PACK_PickFormat(const S3PACK_Pack *pack, SDL_GPUDevice *device, Uint32 key) {
    const S3PACK_Entry *e = S3PACK_Find(pack, key);
    if (!e) return 0;
    const SDL_GPUShaderFormat supported = SDL_GetGPUShaderFormats(device);
    /* Preference order: native binary first, then portable source. */
    static const Uint32 order[] = {SDL_GPU_SHADERFORMAT_METALLIB, SDL_GPU_SHADERFORMAT_DXIL,
                                   SDL_GPU_SHADERFORMAT_SPIRV,    SDL_GPU_SHADERFORMAT_DXBC,
                                   SDL_GPU_SHADERFORMAT_MSL};
    for (size_t i = 0; i < SDL_arraysize(order); ++i) {
        if ((e->format_mask & order[i]) && (supported & order[i])) return order[i];
    }
    return 0;
}

static bool s3pack_decode(const S3PACK_Pack *pack, const S3PACK_BlobRef *ref, void *out,
                          size_t out_size) {
    const Uint8 *src = pack->data + ref->offset;
    if (ref->size == ref->uncompressed_size || !(pack->flags & S3PACK_FLAG_COMPRESSED)) {
        SDL_memcpy(out, src, ref->size);
        return true;
    }
    if (pack->compression == S3PACK_COMPRESSION_LZ4) {
#ifdef S3PACK_LZ4_DECODE
        return S3PACK_LZ4_DECODE(src, ref->size, out, out_size) == (int)ref->uncompressed_size;
#else
        (void)out_size;
        return S3PACK_SetError("s3pack: pack is LZ4 compressed; define S3PACK_LZ4_DECODE before "
                               "including this header, or rebuild the pack with compression=none");
#endif
    }
    if (pack->compression == S3PACK_COMPRESSION_ZSTD) {
#ifdef S3PACK_ZSTD_DECODE
        return S3PACK_ZSTD_DECODE(src, ref->size, out, out_size) == (size_t)ref->uncompressed_size;
#else
        (void)out_size;
        return S3PACK_SetError("s3pack: pack is zstd compressed; define S3PACK_ZSTD_DECODE before "
                               "including this header, or rebuild the pack with compression=none");
#endif
    }
    return S3PACK_SetError("s3pack: unknown compression id %u", (unsigned)pack->compression);
}

size_t S3PACK_ReadBlob(const S3PACK_Pack *pack, Uint32 key, Uint32 format, void *out,
                       size_t out_size) {
    const S3PACK_Entry *e = S3PACK_Find(pack, key);
    if (!e) { S3PACK_SetError("s3pack: no shader with key %u", (unsigned)key); return 0; }
    for (Uint32 i = 0; i < e->blob_count; ++i) {
        if (e->blobs[i].format != format) continue;
        if (!out) return e->blobs[i].uncompressed_size;
        if (out_size < e->blobs[i].uncompressed_size) {
            S3PACK_SetError("s3pack: output buffer too small for key %u", (unsigned)key);
            return 0;
        }
        if (!s3pack_decode(pack, &e->blobs[i], out, out_size)) return 0;
        return e->blobs[i].uncompressed_size;
    }
    S3PACK_SetError("s3pack: key %u has no blob in the requested format", (unsigned)key);
    return 0;
}

typedef struct S3PACK_Scratch {
    void *ptr;
    size_t size;
} S3PACK_Scratch;

static bool s3pack_fetch(const S3PACK_Pack *pack, SDL_GPUDevice *device, Uint32 key,
                         S3PACK_Scratch *scratch, Uint32 *out_format,
                         const S3PACK_Entry **out_entry) {
    const S3PACK_Entry *e = S3PACK_Find(pack, key);
    if (!e) return S3PACK_SetError("s3pack: no shader with key %u in this pack", (unsigned)key);

    const Uint32 format = S3PACK_PickFormat(pack, device, key);
    if (!format) {
        return S3PACK_SetError("s3pack: shader %u has no blob this device can use (pack has 0x%x, "
                               "device supports 0x%x)", (unsigned)key, (unsigned)e->format_mask,
                               (unsigned)SDL_GetGPUShaderFormats(device));
    }

    const size_t needed = S3PACK_ReadBlob(pack, key, format, NULL, 0);
    if (needed == 0) return false;

    scratch->ptr = S3PACK_MALLOC(needed);
    if (!scratch->ptr) return S3PACK_SetError("s3pack: out of memory");
    scratch->size = needed;
    if (S3PACK_ReadBlob(pack, key, format, scratch->ptr, needed) != needed) {
        S3PACK_FREE(scratch->ptr);
        scratch->ptr = NULL;
        return false;
    }
    *out_format = format;
    *out_entry = e;
    return true;
}

SDL_GPUShader *S3PACK_CreateShader(SDL_GPUDevice *device, const S3PACK_Pack *pack, Uint32 key) {
    S3PACK_Scratch scratch = {NULL, 0};
    Uint32 format = 0;
    const S3PACK_Entry *e = NULL;
    if (!s3pack_fetch(pack, device, key, &scratch, &format, &e)) return NULL;

    if (e->stage == S3PACK_STAGE_COMPUTE) {
        S3PACK_FREE(scratch.ptr);
        S3PACK_SetError("s3pack: key %u is a compute shader; use S3PACK_CreateComputePipeline",
                        (unsigned)key);
        return NULL;
    }

    SDL_GPUShaderCreateInfo info;
    SDL_zero(info);
    info.code = (const Uint8 *)scratch.ptr;
    info.code_size = scratch.size;
    info.entrypoint = e->entry_point ? e->entry_point : "main";
    info.format = (SDL_GPUShaderFormat)format;
    info.stage = e->stage == S3PACK_STAGE_VERTEX ? SDL_GPU_SHADERSTAGE_VERTEX
                                                : SDL_GPU_SHADERSTAGE_FRAGMENT;
    info.num_samplers = e->num_samplers;
    info.num_storage_textures = e->num_storage_textures;
    info.num_storage_buffers = e->num_storage_buffers;
    info.num_uniform_buffers = e->num_uniform_buffers;

    SDL_GPUShader *shader = SDL_CreateGPUShader(device, &info);
    S3PACK_FREE(scratch.ptr);
    if (!shader) S3PACK_SetError("s3pack: SDL_CreateGPUShader failed for key %u: %s",
                                 (unsigned)key, SDL_GetError());
    return shader;
}

SDL_GPUComputePipeline *S3PACK_CreateComputePipeline(SDL_GPUDevice *device, const S3PACK_Pack *pack,
                                                     Uint32 key, Uint32 out_threads[3]) {
    S3PACK_Scratch scratch = {NULL, 0};
    Uint32 format = 0;
    const S3PACK_Entry *e = NULL;
    if (!s3pack_fetch(pack, device, key, &scratch, &format, &e)) return NULL;

    if (e->stage != S3PACK_STAGE_COMPUTE) {
        S3PACK_FREE(scratch.ptr);
        S3PACK_SetError("s3pack: key %u is not a compute shader", (unsigned)key);
        return NULL;
    }

    SDL_GPUComputePipelineCreateInfo info;
    SDL_zero(info);
    info.code = (const Uint8 *)scratch.ptr;
    info.code_size = scratch.size;
    info.entrypoint = e->entry_point ? e->entry_point : "main";
    info.format = (SDL_GPUShaderFormat)format;
    info.num_samplers = e->num_samplers;
    info.num_readonly_storage_textures = e->num_storage_textures;
    info.num_readonly_storage_buffers = e->num_storage_buffers;
    info.num_readwrite_storage_textures = e->num_readwrite_storage_textures;
    info.num_readwrite_storage_buffers = e->num_readwrite_storage_buffers;
    info.num_uniform_buffers = e->num_uniform_buffers;
    info.threadcount_x = e->compute_threads[0];
    info.threadcount_y = e->compute_threads[1];
    info.threadcount_z = e->compute_threads[2];

    SDL_GPUComputePipeline *pipeline = SDL_CreateGPUComputePipeline(device, &info);
    S3PACK_FREE(scratch.ptr);
    if (!pipeline) {
        S3PACK_SetError("s3pack: SDL_CreateGPUComputePipeline failed for key %u: %s", (unsigned)key,
                        SDL_GetError());
        return NULL;
    }
    if (out_threads) {
        out_threads[0] = e->compute_threads[0];
        out_threads[1] = e->compute_threads[1];
        out_threads[2] = e->compute_threads[2];
    }
    return pipeline;
}

#endif /* S3PACK_IMPLEMENTATION */
#endif /* S3PACK_H_INCLUDED */
