#include "ssstudio/codegen.h"

#include <algorithm>
#include <iomanip>
#include <sstream>

#include "ssstudio/keys.h"

// The loader template is embedded at build time by tools/embed_file.cmake.
extern const char kS3PackTemplate[];

namespace ssstudio {
namespace {

std::string replace_all(std::string s, const std::string& from, const std::string& to) {
    if (from.empty()) return s;
    std::size_t pos = 0;
    while ((pos = s.find(from, pos)) != std::string::npos) {
        s.replace(pos, from.size(), to);
        pos += to.size();
    }
    return s;
}

std::string hex32(std::uint32_t v) {
    std::ostringstream os;
    os << "0x" << std::hex << std::uppercase << std::setw(8) << std::setfill('0') << v << "u";
    return os.str();
}

std::string banner(const GenInfo& info, const char* file_kind) {
    std::ostringstream os;
    os << "// " << file_kind << " - generated by " << info.tool_version << "\n"
       << "// project: " << info.project_name << "   profile: " << info.profile_name << "\n"
       << "// pack:    " << info.pack_filename << "   layout: " << info.layout.signature() << "\n"
       << "// Do not edit by hand; rebuild instead (or take ownership and stop regenerating).\n";
    return os.str();
}

// C type for a uniform member, with the padding rules HLSL/std140 imply.
struct StructField {
    std::string type;
    std::string name;
    std::uint32_t offset;
    std::uint32_t size;
};

std::string c_scalar(ScalarType t) {
    switch (t) {
        case ScalarType::Bool: return "Sint32";  // HLSL bool is 4 bytes in a cbuffer
        case ScalarType::Int: return "Sint32";
        case ScalarType::UInt: return "Uint32";
        case ScalarType::Double: return "double";
        default: return "float";
    }
}

std::string c_member_type(const UniformMember& m) {
    const std::string base = c_scalar(m.type);
    if (m.rows > 1) return base;  // matrices are emitted as arrays below
    if (m.cols > 1) return base;
    return base;
}

std::string c_member_decl(const UniformMember& m) {
    const std::string base = c_member_type(m);
    std::string decl = base + " " + m.name;
    const std::uint32_t comps = m.rows * m.cols;
    if (comps > 1) decl += "[" + std::to_string(comps) + "]";
    if (m.array_size > 0) decl += "[" + std::to_string(m.array_size) + "]";
    return decl;
}

}  // namespace

// ---------------------------------------------------------------------------
// shaders.h
// ---------------------------------------------------------------------------
std::string generate_id_header(const std::vector<PackShader>& shaders, const GenInfo& info) {
    std::ostringstream os;
    const std::string guard =
        "SSSTUDIO_" + replace_all(info.enum_prefix, "-", "_") + "_IDS_H_INCLUDED";

    os << banner(info, "shader ids") << "#ifndef " << guard << "\n#define " << guard << "\n\n";
    os << "#include <SDL3/SDL_stdinc.h>\n\n";

    if (!info.cpp_namespace.empty()) os << "#ifdef __cplusplus\nnamespace " << info.cpp_namespace << " {\n#endif\n\n";

    os << "/* Shader ids. Keys are " << to_string(KeyStrategy::Explicit)
       << "-stable: once assigned they are pinned in project.toml and never move. */\n";
    os << "typedef enum " << info.enum_prefix << "_Id {\n";

    std::vector<const PackShader*> sorted;
    for (const auto& s : shaders) sorted.push_back(&s);
    std::sort(sorted.begin(), sorted.end(),
              [](const PackShader* a, const PackShader* b) { return a->id < b->id; });

    std::size_t width = 0;
    for (const auto* s : sorted) width = std::max(width, enum_name(info.enum_prefix, s->id).size());

    for (const auto* s : sorted) {
        const std::string name = enum_name(info.enum_prefix, s->id);
        os << "    " << name << std::string(width - name.size(), ' ') << " = " << hex32(s->key)
           << ",  /* " << to_string(s->stage) << ", entry '" << s->entry_point << "' */\n";
    }
    os << "    " << info.enum_prefix << "_COUNT = " << shaders.size() << "\n";
    os << "} " << info.enum_prefix << "_Id;\n\n";

    os << "/* Per-shader resource counts, so a pipeline can be sized at compile time. */\n";
    for (const auto* s : sorted) {
        const std::string n = enum_name(info.enum_prefix, s->id);
        const bool compute = s->stage == Stage::Compute;
        const std::uint32_t ro_tex = compute ? s->reflection.num_readonly_storage_textures()
                                             : s->reflection.num_storage_textures();
        const std::uint32_t ro_buf = compute ? s->reflection.num_readonly_storage_buffers()
                                             : s->reflection.num_storage_buffers();
        os << "#define " << n << "_NUM_SAMPLERS " << s->reflection.num_samplers() << "\n";
        os << "#define " << n << "_NUM_STORAGE_TEXTURES " << ro_tex << "\n";
        os << "#define " << n << "_NUM_STORAGE_BUFFERS " << ro_buf << "\n";
        os << "#define " << n << "_NUM_UNIFORM_BUFFERS " << s->reflection.num_uniform_buffers()
           << "\n";
        if (compute) {
            os << "#define " << n << "_NUM_RW_STORAGE_TEXTURES "
               << s->reflection.num_readwrite_storage_textures() << "\n";
            os << "#define " << n << "_NUM_RW_STORAGE_BUFFERS "
               << s->reflection.num_readwrite_storage_buffers() << "\n";
            os << "#define " << n << "_THREADS_X " << s->reflection.compute_threads[0] << "\n";
            os << "#define " << n << "_THREADS_Y " << s->reflection.compute_threads[1] << "\n";
            os << "#define " << n << "_THREADS_Z " << s->reflection.compute_threads[2] << "\n";
        }
        os << "\n";
    }

    os << "#define " << info.enum_prefix << "_PACK_FILE \"" << info.pack_filename << "\"\n";
    os << "#define " << info.enum_prefix << "_PACK_FORMATS "
       << hex32(info.stats.format_mask) << "\n";
    os << "#define " << info.enum_prefix << "_PACK_LAYOUT \"" << info.layout.signature() << "\"\n";

    if (!info.cpp_namespace.empty()) os << "\n#ifdef __cplusplus\n}  /* namespace */\n#endif\n";
    os << "\n#endif /* " << guard << " */\n";
    return os.str();
}

// ---------------------------------------------------------------------------
// s3pack.h
// ---------------------------------------------------------------------------
std::string generate_loader_header(const GenInfo& info) {
    std::string out = kS3PackTemplate;
    out = replace_all(out, "@TOOL_VERSION@", info.tool_version);
    out = replace_all(out, "@LAYOUT_SIGNATURE@", info.layout.signature());
    out = replace_all(out, "@MAGIC@", info.layout.magic_string());
    out = replace_all(out, "@PACK_EXT@", info.layout.extension);
    out = replace_all(out, "@VERSION_MAJOR@", std::to_string(kPackVersionMajor));
    out = replace_all(out, "@VERSION_MINOR@", std::to_string(kPackVersionMinor));
    return out;
}

// ---------------------------------------------------------------------------
// shaders_embed.h
// ---------------------------------------------------------------------------
std::string generate_embed_header(const std::vector<std::uint8_t>& pack, const GenInfo& info) {
    std::ostringstream os;
    const std::string sym = replace_all(info.enum_prefix, "-", "_");
    os << banner(info, "embedded pack")
       << "#ifndef SSSTUDIO_" << sym << "_EMBED_H_INCLUDED\n#define SSSTUDIO_" << sym
       << "_EMBED_H_INCLUDED\n\n#include <SDL3/SDL_stdinc.h>\n\n";
    os << "static const Uint8 " << sym << "_PACK_BYTES[" << pack.size() << "] = {\n";
    os << std::hex << std::setfill('0');
    for (std::size_t i = 0; i < pack.size(); ++i) {
        if (i % 16 == 0) os << "    ";
        os << "0x" << std::setw(2) << static_cast<int>(pack[i]);
        if (i + 1 < pack.size()) os << ",";
        if (i % 16 == 15 || i + 1 == pack.size()) os << "\n";
        else os << " ";
    }
    os << std::dec;
    os << "};\n\n#define " << sym << "_PACK_SIZE " << pack.size() << "u\n\n";
    os << "#endif\n";
    return os.str();
}

// ---------------------------------------------------------------------------
// Snippets
// ---------------------------------------------------------------------------
std::string snippet_create_shader(const PackShader& s, const GenInfo& info, SnippetFlavor f) {
    const std::string id = enum_name(info.enum_prefix, s.id);
    std::ostringstream os;
    if (f == SnippetFlavor::C) {
        os << "SDL_GPUShader *" << s.id << " = S3PACK_CreateShader(device, &pack, " << id << ");\n"
           << "if (!" << s.id << ") { SDL_Log(\"%s\", S3PACK_GetError()); return false; }\n"
           << "/* release with SDL_ReleaseGPUShader(device, " << s.id << "); */";
    } else {
        os << "s3pack::Shader " << s.id << " = pack.shader(device, " << id << ");\n"
           << "if (!" << s.id << ") { SDL_Log(\"%s\", pack.error()); return false; }\n"
           << "/* released automatically when it goes out of scope */";
    }
    return os.str();
}

std::string snippet_vertex_input_state(const PackShader& s, const GenInfo& info) {
    (void)info;
    if (s.stage != Stage::Vertex || s.reflection.vertex_inputs.empty()) {
        return "/* no vertex inputs: draw with SDL_DrawGPUPrimitives and generate positions in the shader */";
    }
    auto inputs = s.reflection.vertex_inputs;
    std::sort(inputs.begin(), inputs.end(),
              [](const VertexInput& a, const VertexInput& b) { return a.location < b.location; });

    std::ostringstream os;
    std::uint32_t offset = 0;
    os << "/* Vertex layout derived from " << s.id << ". Offsets assume a tightly packed,\n"
       << "   interleaved buffer in location order; reorder if your vertex struct differs. */\n";
    os << "SDL_GPUVertexAttribute attributes[" << inputs.size() << "] = {\n";
    for (const auto& v : inputs) {
        const std::uint32_t size = v.components * 4;
        os << "    { .location = " << v.location << ", .buffer_slot = 0, .format = "
           << v.sdl_vertex_format() << ", .offset = " << offset << " },";
        if (!v.semantic.empty()) os << "  /* " << v.semantic << " " << v.name << " */";
        else os << "  /* " << v.name << " */";
        os << "\n";
        offset += size;
    }
    os << "};\n\n";
    os << "SDL_GPUVertexBufferDescription vertex_buffer = {\n"
       << "    .slot = 0,\n"
       << "    .pitch = " << offset << ",\n"
       << "    .input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX,\n"
       << "    .instance_step_rate = 0,\n};\n\n";
    os << "SDL_GPUVertexInputState vertex_input = {\n"
       << "    .vertex_buffer_descriptions = &vertex_buffer,\n"
       << "    .num_vertex_buffers = 1,\n"
       << "    .vertex_attributes = attributes,\n"
       << "    .num_vertex_attributes = SDL_arraysize(attributes),\n};";
    return os.str();
}

std::string snippet_pipeline(const PackShader& vs, const PackShader& fs, const GenInfo& info,
                             SnippetFlavor f) {
    std::ostringstream os;
    const std::string vget = f == SnippetFlavor::C ? vs.id : vs.id + ".get()";
    const std::string fget = f == SnippetFlavor::C ? fs.id : fs.id + ".get()";
    os << snippet_create_shader(vs, info, f) << "\n";
    os << snippet_create_shader(fs, info, f) << "\n\n";
    os << "SDL_GPUColorTargetDescription color_target = {\n"
       << "    .format = SDL_GetGPUSwapchainTextureFormat(device, window),\n"
       << "    .blend_state = { .enable_blend = false },\n};\n\n";
    os << "SDL_GPUGraphicsPipelineCreateInfo pipeline_info = {\n"
       << "    .vertex_shader = " << vget << ",\n"
       << "    .fragment_shader = " << fget << ",\n";
    if (!vs.reflection.vertex_inputs.empty()) os << "    .vertex_input_state = vertex_input,\n";
    os << "    .primitive_type = SDL_GPU_PRIMITIVETYPE_TRIANGLELIST,\n"
       << "    .rasterizer_state = { .fill_mode = SDL_GPU_FILLMODE_FILL,\n"
       << "                          .cull_mode = SDL_GPU_CULLMODE_NONE },\n"
       << "    .target_info = { .color_target_descriptions = &color_target,\n"
       << "                     .num_color_targets = 1 },\n};\n\n";
    os << "SDL_GPUGraphicsPipeline *pipeline = SDL_CreateGPUGraphicsPipeline(device, &pipeline_info);";
    return os.str();
}

std::string snippet_uniform_struct(const PackShader& s) {
    if (s.reflection.uniform_blocks.empty()) return "/* this shader declares no uniform buffers */";
    std::ostringstream os;
    for (const auto& b : s.reflection.uniform_blocks) {
        os << "/* " << b.name << " - space" << b.set << ", register b" << b.binding << ", "
           << b.size << " bytes.\n"
           << "   Field order and padding mirror the shader's constant buffer layout. */\n";
        os << "typedef struct " << b.name << " {\n";
        std::uint32_t cursor = 0;
        int pad_index = 0;
        for (const auto& m : b.members) {
            if (m.offset > cursor) {
                const std::uint32_t gap = m.offset - cursor;
                os << "    Uint8 _pad" << pad_index++ << "[" << gap << "];\n";
                cursor = m.offset;
            }
            os << "    " << c_member_decl(m) << ";";
            os << "  /* offset " << m.offset << ", " << m.size << " bytes */\n";
            cursor = m.offset + m.size;
        }
        if (b.size > cursor) {
            os << "    Uint8 _pad" << pad_index++ << "[" << (b.size - cursor) << "];\n";
        }
        os << "} " << b.name << ";\n\n";
        os << "SDL_COMPILE_TIME_ASSERT(" << b.name << "_size, sizeof(" << b.name
           << ") == " << b.size << ");\n\n";
    }
    std::string out = os.str();
    if (!out.empty() && out.back() == '\n') out.pop_back();
    return out;
}

std::string snippet_uniform_push(const PackShader& s) {
    if (s.reflection.uniform_blocks.empty()) return "/* this shader declares no uniform buffers */";
    std::ostringstream os;
    const char* fn = s.stage == Stage::Vertex     ? "SDL_PushGPUVertexUniformData"
                     : s.stage == Stage::Fragment ? "SDL_PushGPUFragmentUniformData"
                                                  : "SDL_PushGPUComputeUniformData";
    for (const auto& b : s.reflection.uniform_blocks) {
        const std::uint32_t slot = b.binding;
        os << b.name << " " << b.name << "_data = {0};\n";
        os << "/* fill fields here */\n";
        os << fn << "(command_buffer, " << slot << ", &" << b.name << "_data, sizeof("
           << b.name << "));\n";
    }
    std::string out = os.str();
    if (!out.empty() && out.back() == '\n') out.pop_back();
    return out;
}

std::string snippet_samplers(const PackShader& s) {
    std::vector<const Resource*> sampled;
    for (const auto& r : s.reflection.resources)
        if (r.kind == ResourceKind::SampledTexture) sampled.push_back(&r);
    if (sampled.empty()) return "/* this shader samples no textures */";

    std::ostringstream os;
    os << "SDL_GPUSamplerCreateInfo sampler_info = {\n"
       << "    .min_filter = SDL_GPU_FILTER_LINEAR,\n"
       << "    .mag_filter = SDL_GPU_FILTER_LINEAR,\n"
       << "    .mipmap_mode = SDL_GPU_SAMPLERMIPMAPMODE_LINEAR,\n"
       << "    .address_mode_u = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,\n"
       << "    .address_mode_v = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,\n"
       << "    .address_mode_w = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,\n};\n"
       << "SDL_GPUSampler *sampler = SDL_CreateGPUSampler(device, &sampler_info);\n\n";
    os << "SDL_GPUTextureSamplerBinding bindings[" << sampled.size() << "] = {\n";
    for (const auto* r : sampled) {
        os << "    { .texture = /* " << r->name << " */ NULL, .sampler = sampler },  /* space"
           << r->set << ", t" << r->binding << " */\n";
    }
    os << "};\n";
    const char* bind = s.stage == Stage::Vertex     ? "SDL_BindGPUVertexSamplers"
                       : s.stage == Stage::Fragment ? "SDL_BindGPUFragmentSamplers"
                                                    : "SDL_BindGPUComputeSamplers";
    os << bind << "(render_pass, 0, bindings, SDL_arraysize(bindings));";
    return os.str();
}

std::string snippet_compute_dispatch(const PackShader& s, const GenInfo& info, SnippetFlavor f) {
    const std::string id = enum_name(info.enum_prefix, s.id);
    std::ostringstream os;
    const auto& t = s.reflection.compute_threads;
    if (f == SnippetFlavor::C) {
        os << "Uint32 threads[3];\n"
           << "SDL_GPUComputePipeline *pipeline =\n"
           << "    S3PACK_CreateComputePipeline(device, &pack, " << id << ", threads);\n\n"
           << "SDL_GPUComputePass *pass = SDL_BeginGPUComputePass(command_buffer,\n"
           << "                                                   storage_texture_bindings, 1,\n"
           << "                                                   storage_buffer_bindings, 0);\n"
           << "SDL_BindGPUComputePipeline(pass, pipeline);\n"
           << "SDL_DispatchGPUCompute(pass, (width + " << t[0] << " - 1) / " << t[0]
           << ",\n                            (height + " << t[1] << " - 1) / " << t[1] << ", 1);\n"
           << "SDL_EndGPUComputePass(pass);";
    } else {
        os << "s3pack::ComputePipeline " << s.id << " = pack.compute(device, " << id << ");\n\n"
           << "SDL_GPUComputePass *pass = SDL_BeginGPUComputePass(command_buffer,\n"
           << "                                                   storage_texture_bindings, 1,\n"
           << "                                                   storage_buffer_bindings, 0);\n"
           << "SDL_BindGPUComputePipeline(pass, " << s.id << ".get());\n"
           << "SDL_DispatchGPUCompute(pass, " << s.id << ".groups_for(width, 0),\n"
           << "                            " << s.id << ".groups_for(height, 1), 1);\n"
           << "SDL_EndGPUComputePass(pass);";
    }
    return os.str();
}

// ---------------------------------------------------------------------------
// SHADERS.md
// ---------------------------------------------------------------------------
std::string generate_docs(const std::vector<PackShader>& shaders, const GenInfo& info) {
    std::ostringstream os;
    const bool compute_only = info.stats.compute_only;

    os << "# " << info.project_name << " - shader pack\n\n";
    os << "Generated by " << info.tool_version << " (profile `" << info.profile_name << "`) on "
       << info.build_time << ".\n\n";

    os << "| | |\n|---|---|\n";
    os << "| Pack file | `" << info.pack_filename << "` |\n";
    os << "| Shaders | " << shaders.size() << " |\n";
    os << "| Formats | " << format_mask_to_string(info.stats.format_mask) << " |\n";
    os << "| Compression | " << to_string(info.compression) << " |\n";
    os << "| Size | " << info.stats.total_bytes << " bytes (from "
       << info.stats.raw_bytes << " raw) |\n";
    os << "| Layout | `" << info.layout.signature() << "` |\n";
    if (compute_only) os << "| Kind | compute-only pack |\n";
    os << "\n";

    os << "## Loading\n\n";
    os << "```c\n#define S3PACK_IMPLEMENTATION\n#include \"s3pack.h\"\n#include \"shaders.h\"\n\n"
       << "S3PACK_Pack pack;\nif (!S3PACK_OpenFile(&pack, \"" << info.pack_filename
       << "\")) {\n    SDL_Log(\"%s\", S3PACK_GetError());\n}\n```\n\n";
    os << "```cpp\n// C++: the pack, shaders and pipelines release themselves.\n"
       << "auto pack = s3pack::Pack::open_file(\"" << info.pack_filename << "\");\n"
       << "if (!pack) SDL_Log(\"%s\", pack.error());\n```\n\n";
    // Only warn when compression was actually applied: below the threshold every
    // blob is stored raw, and a note telling the reader to define a decoder macro
    // they do not need would be wrong.
    const bool actually_compressed =
        info.compression != Compression::None && info.stats.stored_bytes < info.stats.raw_bytes;
    if (actually_compressed) {
        os << "> This pack is " << to_string(info.compression)
           << " compressed. Define `S3PACK_"
           << (info.compression == Compression::LZ4 ? "LZ4" : "ZSTD")
           << "_DECODE` before including `s3pack.h`, or rebuild with `compression = \"none\"`.\n\n";
    }

    os << "## Shaders\n\n";
    os << "| Id | Key | Stage | Entry | Language | Formats |\n|---|---|---|---|---|---|\n";
    std::vector<const PackShader*> sorted;
    for (const auto& s : shaders) sorted.push_back(&s);
    std::sort(sorted.begin(), sorted.end(),
              [](const PackShader* a, const PackShader* b) { return a->id < b->id; });
    for (const auto* s : sorted) {
        std::uint32_t mask = 0;
        for (const auto& [fmt, bytes] : s->blobs) {
            (void)bytes;
            mask |= fmt;
        }
        os << "| `" << enum_name(info.enum_prefix, s->id) << "` | " << hex32(s->key) << " | "
           << to_string(s->stage) << " | `" << s->entry_point << "` | " << to_string(s->language)
           << " | " << format_mask_to_string(mask) << " |\n";
    }
    os << "\n";

    for (const auto* sp : sorted) {
        const PackShader& s = *sp;
        const bool compute = s.stage == Stage::Compute;
        os << "---\n\n### " << s.id << "\n\n";
        os << "`" << enum_name(info.enum_prefix, s.id) << "` = " << hex32(s.key) << " - "
           << to_string(s.stage) << ", entry `" << s.entry_point << "`";
        if (compute) {
            os << ", thread group " << s.reflection.compute_threads[0] << "x"
               << s.reflection.compute_threads[1] << "x" << s.reflection.compute_threads[2];
        }
        os << ".\n\n";

        if (const auto it = info.provenance.find(s.id); it != info.provenance.end()) {
            const Provenance& origin = it->second;
            os << "> Imported";
            if (!origin.author.empty()) os << " - by " << origin.author;
            if (!origin.imported.empty()) os << " on " << origin.imported;
            os << ".\n";
            if (!origin.url.empty()) os << "> Source: <" << origin.url << ">\n";
            if (!origin.licence.empty()) os << "> Licence: " << origin.licence << "\n";
            os << "\n";
        }

        os << "Create-info counts: samplers " << s.reflection.num_samplers()
           << ", storage textures "
           << (compute ? s.reflection.num_readonly_storage_textures()
                       : s.reflection.num_storage_textures())
           << ", storage buffers "
           << (compute ? s.reflection.num_readonly_storage_buffers()
                       : s.reflection.num_storage_buffers())
           << ", uniform buffers " << s.reflection.num_uniform_buffers();
        if (compute) {
            os << ", read-write textures " << s.reflection.num_readwrite_storage_textures()
               << ", read-write buffers " << s.reflection.num_readwrite_storage_buffers();
        }
        os << ".\n\n";

        if (!s.reflection.resources.empty()) {
            os << "**Resources**\n\n| Name | Kind | Space/Set | Register | Notes |\n"
                  "|---|---|---|---|---|\n";
            for (const auto& r : s.reflection.resources) {
                os << "| `" << r.name << "` | " << to_string(r.kind) << " | " << r.set << " | "
                   << r.binding << " | " << to_string(r.dim);
                if (r.writable) os << ", read-write";
                if (r.struct_stride) os << ", stride " << r.struct_stride;
                os << " |\n";
            }
            os << "\n";
        }

        if (!s.reflection.uniform_blocks.empty()) {
            os << "**Uniform buffers**\n\n| Block | Space/Set | Register | Size | Members |\n"
                  "|---|---|---|---|---|\n";
            for (const auto& b : s.reflection.uniform_blocks) {
                os << "| `" << b.name << "` | " << b.set << " | b" << b.binding << " | " << b.size
                   << " B | ";
                for (std::size_t i = 0; i < b.members.size(); ++i) {
                    if (i) os << ", ";
                    os << "`" << b.members[i].c_type() << " " << b.members[i].name << "`";
                }
                os << " |\n";
            }
            os << "\n```c\n" << snippet_uniform_struct(s) << "\n```\n\n";
            os << "```c\n" << snippet_uniform_push(s) << "\n```\n\n";
        }

        if (!compute && !s.reflection.vertex_inputs.empty()) {
            os << "**Vertex inputs**\n\n| Location | Name | Semantic | Suggested format |\n"
                  "|---|---|---|---|\n";
            auto vi = s.reflection.vertex_inputs;
            std::sort(vi.begin(), vi.end(),
                      [](const VertexInput& a, const VertexInput& b) { return a.location < b.location; });
            for (const auto& v : vi) {
                os << "| " << v.location << " | `" << v.name << "` | "
                   << (v.semantic.empty() ? "-" : v.semantic) << " | `" << v.sdl_vertex_format()
                   << "` |\n";
            }
            os << "\n```c\n" << snippet_vertex_input_state(s, info) << "\n```\n\n";
        }

        os << "**Create (C)**\n\n```c\n" << snippet_create_shader(s, info, SnippetFlavor::C)
           << "\n```\n\n";
        os << "**Create (C++)**\n\n```cpp\n"
           << snippet_create_shader(s, info, SnippetFlavor::CppRaii) << "\n```\n\n";

        if (compute) {
            os << "**Dispatch**\n\n```c\n"
               << snippet_compute_dispatch(s, info, SnippetFlavor::C) << "\n```\n\n";
            os << "```cpp\n" << snippet_compute_dispatch(s, info, SnippetFlavor::CppRaii)
               << "\n```\n\n";
        }

        const std::string samplers = snippet_samplers(s);
        if (samplers.rfind("/*", 0) != 0) {
            os << "**Samplers**\n\n```c\n" << samplers << "\n```\n\n";
        }
    }

    // Pipeline example pairs the first vertex/fragment shaders it finds.
    if (!compute_only) {
        const PackShader* vs = nullptr;
        const PackShader* fs = nullptr;
        for (const auto* s : sorted) {
            if (!vs && s->stage == Stage::Vertex) vs = s;
            if (!fs && s->stage == Stage::Fragment) fs = s;
        }
        if (vs && fs) {
            os << "---\n\n## Pipeline example\n\n```c\n"
               << snippet_pipeline(*vs, *fs, info, SnippetFlavor::C) << "\n```\n\n";
            os << "```cpp\n" << snippet_pipeline(*vs, *fs, info, SnippetFlavor::CppRaii)
               << "\n```\n";
        }
    }

    os << "\n---\n\n## Keys\n\nKeys are 32-bit values (never strings). This pack uses the `"
       << to_string(KeyStrategy::Explicit)
       << "` strategy by default: the first build derives a key with FNV-1a 32 of the shader id, "
          "pins it in `project.toml`, and never changes it again - so shipping a new pack to an "
          "old binary keeps working.\n";
    return os.str();
}

// ---------------------------------------------------------------------------
// shaders_meta.toml
// ---------------------------------------------------------------------------
std::string generate_meta_toml(const std::vector<PackShader>& shaders, const GenInfo& info) {
    std::ostringstream os;
    os << "# Build provenance for " << info.pack_filename << ".\n"
       << "# This file is optional at runtime. If you ship it, every field here is yours to\n"
       << "# edit or extend - the loader never reads it unless you ask it to.\n\n";
    os << "[build]\n";
    os << "tool = \"" << info.tool_version << "\"\n";
    os << "project = \"" << info.project_name << "\"\n";
    os << "profile = \"" << info.profile_name << "\"\n";
    os << "time = \"" << info.build_time << "\"\n";
    os << "formats = \"" << format_mask_to_string(info.stats.format_mask) << "\"\n";
    os << "compression = \"" << to_string(info.compression) << "\"\n";
    os << "total_bytes = " << info.stats.total_bytes << "\n";
    if (!info.defines.empty()) {
        os << "defines = [";
        for (std::size_t i = 0; i < info.defines.size(); ++i) {
            if (i) os << ", ";
            os << "\"" << info.defines[i] << "\"";
        }
        os << "]\n";
    }
    os << "\n[layout]\n";
    os << "signature = \"" << info.layout.signature() << "\"\n";
    os << "magic = \"" << info.layout.magic_string() << "\"\n";
    os << "extension = \"" << info.layout.extension << "\"\n";
    os << "header_preset = \"" << to_string(info.layout.header_preset) << "\"\n";
    os << "entry_sort = \"" << to_string(info.layout.entry_sort) << "\"\n";
    os << "alignment = " << info.layout.alignment << "\n";
    os << "key_bits = " << (info.layout.key16 ? 16 : 32) << "\n\n";

    for (const auto& s : shaders) {
        os << "[[shader]]\n";
        os << "id = \"" << s.id << "\"\n";
        os << "key = " << s.key << "\n";
        os << "enum = \"" << enum_name(info.enum_prefix, s.id) << "\"\n";
        os << "stage = \"" << to_string(s.stage) << "\"\n";
        os << "language = \"" << to_string(s.language) << "\"\n";
        os << "entry = \"" << s.entry_point << "\"\n";
        if (s.stage == Stage::Compute) {
            os << "threads = [" << s.reflection.compute_threads[0] << ", "
               << s.reflection.compute_threads[1] << ", " << s.reflection.compute_threads[2]
               << "]\n";
        }
        os << "\n";
    }
    return os.str();
}

std::string generate_reflection_json(const std::vector<PackShader>& shaders) {
    std::ostringstream os;
    os << "{\n  \"shaders\": [\n";
    for (std::size_t i = 0; i < shaders.size(); ++i) {
        os << "    {\"id\":\"" << shaders[i].id << "\",\"key\":" << shaders[i].key
           << ",\"reflection\":" << reflection_to_json(shaders[i].reflection) << "}";
        if (i + 1 < shaders.size()) os << ",";
        os << "\n";
    }
    os << "  ]\n}\n";
    return os.str();
}

std::string generate_cmake_snippet(const GenInfo& info) {
    std::ostringstream os;
    os << "# Rebuilds the shader pack whenever a source shader changes.\n"
       << "# add_shader_pack(TARGET my_game PROJECT ${CMAKE_SOURCE_DIR}/shaders/MyShaders.ssstudio)\n\n"
       << "find_program(SSSTUDIO_CLI ssstudio REQUIRED)\n\n"
       << "function(add_shader_pack)\n"
       << "    cmake_parse_arguments(ARG \"\" \"TARGET;PROJECT;PROFILE;OUTPUT\" \"\" ${ARGN})\n"
       << "    if(NOT ARG_PROFILE)\n        set(ARG_PROFILE \"" << info.profile_name << "\")\n    endif()\n"
       << "    if(NOT ARG_OUTPUT)\n        set(ARG_OUTPUT \"${CMAKE_CURRENT_BINARY_DIR}/shaders\")\n    endif()\n"
       << "    file(GLOB_RECURSE SHADER_SOURCES \"${ARG_PROJECT}/shaders/*\")\n"
       << "    add_custom_command(\n"
       << "        OUTPUT \"${ARG_OUTPUT}/" << info.pack_filename << "\"\n"
       << "        COMMAND ${SSSTUDIO_CLI} build \"${ARG_PROJECT}\" --profile ${ARG_PROFILE} --out \"${ARG_OUTPUT}\"\n"
       << "        DEPENDS ${SHADER_SOURCES} \"${ARG_PROJECT}/project.toml\"\n"
       << "        COMMENT \"Building shader pack\"\n"
       << "        VERBATIM)\n"
       << "    add_custom_target(${ARG_TARGET}_shaders DEPENDS \"${ARG_OUTPUT}/"
       << info.pack_filename << "\")\n"
       << "    add_dependencies(${ARG_TARGET} ${ARG_TARGET}_shaders)\n"
       << "    target_include_directories(${ARG_TARGET} PRIVATE \"${ARG_OUTPUT}\")\n"
       << "endfunction()\n";
    return os.str();
}

}  // namespace ssstudio
